language: c

os:
  - linux

compiler:
  - clang
  - gcc

sudo: required

before_install:
  - sudo apt-get update --quiet --assume-yes
  - sudo apt-get install splint --quiet --assume-yes
  - sudo apt-get install valgrind --quiet --assume-yes

before_script: 
  - mkdir .deps
  - curl https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.26.tar.bz2 | tar xjf - -C .deps
  - pushd .deps/libgpg-error-1.26 && ./configure && make && sudo make install && popd
  - curl https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.7.6.tar.bz2 | tar xjf - -C .deps
  - pushd .deps/libgcrypt-1.7.6 && ./configure && make && sudo make install && popd
  - curl https://download.libsodium.org/libsodium/releases/libsodium-1.0.11.tar.gz | tar xzf - -C .deps
  - pushd .deps/libsodium-1.0.11 && ./autogen.sh && ./configure && make && sudo make install && popd
  - git clone https://github.com/twstrike/ed448goldilocks-decaf.git .deps/decaf
  - pushd .deps/decaf && ./autogen.sh && ./configure && make && sudo make install && popd
  - git clone https://github.com/twstrike/cramershoup.git .deps/cramershoup
  - pushd .deps/cramershoup && ./autogen.sh && ./configure CFLAGS="-DFAST_RANDOM" && make && sudo make install && popd

script:
  - export CFLAGS="-g -ggdb3 -O0"
  - export CXXFLAGS="-g -ggdb3 -O0"
  - export LDFLAGS="-g -ggdb3 -O0"
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - ./autogen.sh && ./configure && make ci
