language: c

sudo: required

before_install:
  - sudo apt-get update --quiet --assume-yes
  - sudo apt-get install splint --quiet --assume-yes
  - sudo apt-get install valgrind --quiet --assume-yes

script: autoconf --version && ./autogen.sh && ./configure && make ci
