#
#  This file is part of the Off-the-Record Next Generation Messaging
#  library (libotr-ng).
#
#  Copyright (C) 2016-2018, the libotr-ng contributors.
#
#  This library is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this library.  If not, see <http://www.gnu.org/licenses/>.
#

language: c
#cache: ccache

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov
            - valgrind

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: clang
      env: T=normal
    - os: linux
      dist: trusty
      compiler: gcc
      env: T=normal
    - os: linux
      dist: precise
      compiler: clang
      env: T=normal
    - os: linux
      dist: precise
      compiler: gcc
      env: T=normal
    - os: osx
      compiler: clang
      env: T=normal
    - os: linux
      compiler: gcc
      dist: precise
      env: T=coverage
    - os: linux
      dist: trusty
      compiler: clang
      env: T=style
    - os: linux
      compiler: gcc
      dist: precise
      env: T=full-valgrind-checks
    - os: linux
      compiler: gcc
      dist: precise
      env: T=ctgrind
  allow_failures:
    - os: osx
      compiler: clang
      env: T=normal
    - os: linux
      compiler: gcc
      dist: precise
      env: T=ctgrind

sudo: required

notifications:
  irc:
    channels:
      - "irc.oftc.net#cad"
    on_success: never
    on_failure: always

before_install:
# Update the repo

- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update --quiet --assume-yes; fi

# Dependencies
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew cleanup; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install splint && brew install valgrind && brew install curl && brew install glib; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install splint --quiet --assume-yes; fi
- if [[ "$T" = "coverage" ]]; then sudo apt-get install splint --quiet --assume-yes; fi
- if [[ "$T" = "style" ]]; then sudo apt-get install clang-format-3.5 --quiet --assume-yes; fi

before_script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew install libgcrypt || brew outdated libgcrypt || brew upgrade libgcrypt &&
      brew install libsodium || brew outdated libsodium || brew upgrade libsodium;
    fi
  - mkdir .deps
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      curl https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.26.tar.bz2 | tar xjf - -C .deps &&
          pushd .deps/libgpg-error-1.26 && ./configure && make && sudo make install && popd &&
      curl https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.1.tar.bz2 | tar xjf - -C .deps &&
          pushd .deps/libgcrypt-1.8.1 && ./configure && make && sudo make install && popd &&
      git clone --depth=1 https://github.com/jedisct1/libsodium.git .deps/libsodium &&
          pushd .deps/libsodium && ./autogen.sh && ./configure && make && sudo make install && popd;
    fi
  - if [[ "$T" = "ctgrind" ]]; then
      git clone --depth=1 https://github.com/claucece/ctgrind .deps/ctgrind &&
          pushd .deps/ctgrind && ./autogen.sh && ./configure && make && sudo make install && popd;
    fi
  - git clone --depth=1 https://bugs.otr.im/lib/libotr.git .deps/libotr
  - pushd .deps/libotr && ./bootstrap && ./configure && make && sudo make install && popd
  - git clone --depth=1 https://github.com/otrv4/libgoldilocks .deps/libgoldilocks
  - pushd .deps/libgoldilocks && ./autogen.sh && ./configure && make && sudo make install && popd

script:
  - export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}
  - export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:${PKG_CONFIG_PATH}"
  - |
      if [ "$T" = "coverage" ]; then
           ./autogen.sh
           ./configure --disable-shared --enable-code-coverage
           make ci
           make coverage-check
      fi
  - |
      if [ "$T" = "full-valgrind-checks" ]; then
           ./autogen.sh
           ./configure --enable-valgrind
           make check-valgrind
      fi
  - |
      if [ "$T" = "normal" ]; then
           ./autogen.sh
           ./configure --disable-shared
           make ci
      fi
  - |
      if [ "$T" = "style" ]; then
           ./autogen.sh
           ./configure --disable-shared
           make ci
           make code-style-doctor
      fi
  - |
      if [ "$T" = "ctgrind" ]; then
           ./autogen.sh
           ./configure --with-ctgrind
           make ci
      fi
